// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM activities WHERE source = $1 AND source_id = $2
`

type DeleteActivityParams struct {
	Source   string `json:"source"`
	SourceID string `json:"source_id"`
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivity, arg.Source, arg.SourceID)
	return err
}

const upsertActivity = `-- name: UpsertActivity :one
INSERT INTO activities (user_id, source, source_id, start_time, sport_type, raw_summary)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (source, source_id) DO UPDATE
SET start_time  = EXCLUDED.start_time,
    sport_type  = EXCLUDED.sport_type,
    raw_summary = EXCLUDED.raw_summary
RETURNING id
`

type UpsertActivityParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	Source     string          `json:"source"`
	SourceID   string          `json:"source_id"`
	StartTime  time.Time       `json:"start_time"`
	SportType  string          `json:"sport_type"`
	RawSummary json.RawMessage `json:"raw_summary"`
}

func (q *Queries) UpsertActivity(ctx context.Context, arg UpsertActivityParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, upsertActivity,
		arg.UserID,
		arg.Source,
		arg.SourceID,
		arg.StartTime,
		arg.SportType,
		arg.RawSummary,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertActivityStream = `-- name: UpsertActivityStream :exec
INSERT INTO activity_streams (activity_id, time_offset_s, hr, pace_s_per_km, cadence, power_w, altitude_m, lat, lng)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (activity_id) DO UPDATE
SET time_offset_s = EXCLUDED.time_offset_s,
    hr            = EXCLUDED.hr,
    pace_s_per_km = EXCLUDED.pace_s_per_km,
    cadence       = EXCLUDED.cadence,
    power_w       = EXCLUDED.power_w,
    altitude_m    = EXCLUDED.altitude_m,
    lat           = EXCLUDED.lat,
    lng           = EXCLUDED.lng
`

type UpsertActivityStreamParams struct {
	ActivityID  uuid.UUID `json:"activity_id"`
	TimeOffsetS []int32   `json:"time_offset_s"`
	Hr          []int32   `json:"hr"`
	PaceSPerKm  []string  `json:"pace_s_per_km"`
	Cadence     []int32   `json:"cadence"`
	PowerW      []int32   `json:"power_w"`
	AltitudeM   []string  `json:"altitude_m"`
	Lat         []string  `json:"lat"`
	Lng         []string  `json:"lng"`
}

func (q *Queries) UpsertActivityStream(ctx context.Context, arg UpsertActivityStreamParams) error {
	_, err := q.db.ExecContext(ctx, upsertActivityStream,
		arg.ActivityID,
		pq.Array(arg.TimeOffsetS),
		pq.Array(arg.Hr),
		pq.Array(arg.PaceSPerKm),
		pq.Array(arg.Cadence),
		pq.Array(arg.PowerW),
		pq.Array(arg.AltitudeM),
		pq.Array(arg.Lat),
		pq.Array(arg.Lng),
	)
	return err
}
