// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStravaConnection = `-- name: CreateStravaConnection :one
INSERT INTO strava_connections (user_id, athlete_id, access_token, refresh_token, expires_at, scope)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, athlete_id, access_token, refresh_token, expires_at, scope, created_at, updated_at
`

type CreateStravaConnectionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	AthleteID    int64     `json:"athlete_id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	Scope        string    `json:"scope"`
}

func (q *Queries) CreateStravaConnection(ctx context.Context, arg CreateStravaConnectionParams) (StravaConnection, error) {
	row := q.db.QueryRowContext(ctx, createStravaConnection,
		arg.UserID,
		arg.AthleteID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scope,
	)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name) VALUES ($1) RETURNING id, display_name, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, displayName sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.display_name, users.created_at, users.updated_at FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.id = $1 AND sessions.expires_at > now()
`

type GetSessionUserRow struct {
	User User `json:"user"`
}

func (q *Queries) GetSessionUser(ctx context.Context, id string) (GetSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, id)
	var i GetSessionUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.DisplayName,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getStravaConnectionByAthleteID = `-- name: GetStravaConnectionByAthleteID :one
SELECT user_id, athlete_id, access_token, refresh_token, expires_at, scope, created_at, updated_at FROM strava_connections WHERE athlete_id = $1
`

func (q *Queries) GetStravaConnectionByAthleteID(ctx context.Context, athleteID int64) (StravaConnection, error) {
	row := q.db.QueryRowContext(ctx, getStravaConnectionByAthleteID, athleteID)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStravaConnectionByUserID = `-- name: GetStravaConnectionByUserID :one
SELECT user_id, athlete_id, access_token, refresh_token, expires_at, scope, created_at, updated_at FROM strava_connections WHERE user_id = $1
`

func (q *Queries) GetStravaConnectionByUserID(ctx context.Context, userID uuid.UUID) (StravaConnection, error) {
	row := q.db.QueryRowContext(ctx, getStravaConnectionByUserID, userID)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStravaTokens = `-- name: UpdateStravaTokens :exec
UPDATE strava_connections
SET access_token = $2, refresh_token = $3, expires_at = $4, scope = $5, updated_at = now()
WHERE user_id = $1
`

type UpdateStravaTokensParams struct {
	UserID       uuid.UUID `json:"user_id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	Scope        string    `json:"scope"`
}

func (q *Queries) UpdateStravaTokens(ctx context.Context, arg UpdateStravaTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateStravaTokens,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scope,
	)
	return err
}
