// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const insertRunnerFact = `-- name: InsertRunnerFact :one
INSERT INTO runner_facts (user_id, type, status, value, source_message_id, salience)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, status, value, source_message_id, salience, created_at, updated_at
`

type InsertRunnerFactParams struct {
	UserID          uuid.UUID       `json:"user_id"`
	Type            string          `json:"type"`
	Status          string          `json:"status"`
	Value           json.RawMessage `json:"value"`
	SourceMessageID uuid.UUID       `json:"source_message_id"`
	Salience        sql.NullInt16   `json:"salience"`
}

func (q *Queries) InsertRunnerFact(ctx context.Context, arg InsertRunnerFactParams) (RunnerFact, error) {
	row := q.db.QueryRowContext(ctx, insertRunnerFact,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.Value,
		arg.SourceMessageID,
		arg.Salience,
	)
	var i RunnerFact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Value,
		&i.SourceMessageID,
		&i.Salience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRunnerFacts = `-- name: ListActiveRunnerFacts :many
SELECT id, user_id, type, status, value, source_message_id, salience, created_at, updated_at FROM runner_facts
WHERE user_id = $1 AND status = 'active'
ORDER BY salience DESC, updated_at DESC
`

func (q *Queries) ListActiveRunnerFacts(ctx context.Context, userID uuid.UUID) ([]RunnerFact, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRunnerFacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunnerFact
	for rows.Next() {
		var i RunnerFact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Value,
			&i.SourceMessageID,
			&i.Salience,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunnerFactStatus = `-- name: UpdateRunnerFactStatus :exec
UPDATE runner_facts SET status = $2, updated_at = now()
WHERE id = $1 AND user_id = $3
`

type UpdateRunnerFactStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateRunnerFactStatus(ctx context.Context, arg UpdateRunnerFactStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunnerFactStatus, arg.ID, arg.Status, arg.UserID)
	return err
}
