// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: garmin.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteGarminConnection = `-- name: DeleteGarminConnection :exec
DELETE FROM garmin_connections WHERE user_id = $1
`

func (q *Queries) DeleteGarminConnection(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGarminConnection, userID)
	return err
}

const getGarminConnection = `-- name: GetGarminConnection :one
SELECT user_id, oauth_token, oauth_secret, display_name, full_name, connected_at, last_sync FROM garmin_connections WHERE user_id = $1
`

func (q *Queries) GetGarminConnection(ctx context.Context, userID uuid.UUID) (GarminConnection, error) {
	row := q.db.QueryRowContext(ctx, getGarminConnection, userID)
	var i GarminConnection
	err := row.Scan(
		&i.UserID,
		&i.OauthToken,
		&i.OauthSecret,
		&i.DisplayName,
		&i.FullName,
		&i.ConnectedAt,
		&i.LastSync,
	)
	return i, err
}

const listGarminConnections = `-- name: ListGarminConnections :many
SELECT user_id, oauth_token, oauth_secret, display_name, full_name, connected_at, last_sync FROM garmin_connections
`

func (q *Queries) ListGarminConnections(ctx context.Context) ([]GarminConnection, error) {
	rows, err := q.db.QueryContext(ctx, listGarminConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GarminConnection
	for rows.Next() {
		var i GarminConnection
		if err := rows.Scan(
			&i.UserID,
			&i.OauthToken,
			&i.OauthSecret,
			&i.DisplayName,
			&i.FullName,
			&i.ConnectedAt,
			&i.LastSync,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGarminLastSync = `-- name: UpdateGarminLastSync :exec
UPDATE garmin_connections SET last_sync = $2 WHERE user_id = $1
`

type UpdateGarminLastSyncParams struct {
	UserID   uuid.UUID    `json:"user_id"`
	LastSync sql.NullTime `json:"last_sync"`
}

func (q *Queries) UpdateGarminLastSync(ctx context.Context, arg UpdateGarminLastSyncParams) error {
	_, err := q.db.ExecContext(ctx, updateGarminLastSync, arg.UserID, arg.LastSync)
	return err
}

const upsertGarminConnection = `-- name: UpsertGarminConnection :one
INSERT INTO garmin_connections (user_id, oauth_token, oauth_secret, display_name, full_name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET oauth_token  = EXCLUDED.oauth_token,
    oauth_secret = EXCLUDED.oauth_secret,
    display_name = EXCLUDED.display_name,
    full_name    = EXCLUDED.full_name,
    connected_at = now()
RETURNING user_id, oauth_token, oauth_secret, display_name, full_name, connected_at, last_sync
`

type UpsertGarminConnectionParams struct {
	UserID      uuid.UUID `json:"user_id"`
	OauthToken  string    `json:"oauth_token"`
	OauthSecret string    `json:"oauth_secret"`
	DisplayName string    `json:"display_name"`
	FullName    string    `json:"full_name"`
}

func (q *Queries) UpsertGarminConnection(ctx context.Context, arg UpsertGarminConnectionParams) (GarminConnection, error) {
	row := q.db.QueryRowContext(ctx, upsertGarminConnection,
		arg.UserID,
		arg.OauthToken,
		arg.OauthSecret,
		arg.DisplayName,
		arg.FullName,
	)
	var i GarminConnection
	err := row.Scan(
		&i.UserID,
		&i.OauthToken,
		&i.OauthSecret,
		&i.DisplayName,
		&i.FullName,
		&i.ConnectedAt,
		&i.LastSync,
	)
	return i, err
}
