// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (user_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, content, tool_name, tool_payload, created_at
`

type InsertMessageParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
	Content string    `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage, arg.UserID, arg.Role, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.ToolName,
		&i.ToolPayload,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, user_id, role, content, tool_name, tool_payload, created_at FROM (
    SELECT id, user_id, role, content, tool_name, tool_payload, created_at FROM messages
    WHERE user_id = $1
    ORDER BY created_at DESC, id DESC
    LIMIT $2
) AS recent
ORDER BY created_at ASC, id ASC
`

type ListRecentMessagesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMessages, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.ToolName,
			&i.ToolPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
