// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getActivityStream = `-- name: GetActivityStream :one
SELECT activity_id, time_offset_s, hr, pace_s_per_km, cadence, power_w, altitude_m, lat, lng, extra FROM activity_streams WHERE activity_id = $1
`

func (q *Queries) GetActivityStream(ctx context.Context, activityID uuid.UUID) (ActivityStream, error) {
	row := q.db.QueryRowContext(ctx, getActivityStream, activityID)
	var i ActivityStream
	err := row.Scan(
		&i.ActivityID,
		pq.Array(&i.TimeOffsetS),
		pq.Array(&i.Hr),
		pq.Array(&i.PaceSPerKm),
		pq.Array(&i.Cadence),
		pq.Array(&i.PowerW),
		pq.Array(&i.AltitudeM),
		pq.Array(&i.Lat),
		pq.Array(&i.Lng),
		&i.Extra,
	)
	return i, err
}

const listActivitiesByUser = `-- name: ListActivitiesByUser :many
SELECT id, user_id, source, source_id, start_time, sport_type, raw_summary, ingested_at FROM activities
WHERE user_id = $1 AND start_time >= $2
ORDER BY start_time ASC
`

type ListActivitiesByUserParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) ListActivitiesByUser(ctx context.Context, arg ListActivitiesByUserParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByUser, arg.UserID, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.SourceID,
			&i.StartTime,
			&i.SportType,
			&i.RawSummary,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityStreamsByUser = `-- name: ListActivityStreamsByUser :many
SELECT s.activity_id, s.time_offset_s, s.hr, s.pace_s_per_km, s.cadence, s.power_w, s.altitude_m, s.lat, s.lng, s.extra
FROM activity_streams s
JOIN activities a ON a.id = s.activity_id
WHERE a.user_id = $1 AND a.start_time >= $2
`

type ListActivityStreamsByUserParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) ListActivityStreamsByUser(ctx context.Context, arg ListActivityStreamsByUserParams) ([]ActivityStream, error) {
	rows, err := q.db.QueryContext(ctx, listActivityStreamsByUser, arg.UserID, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityStream
	for rows.Next() {
		var i ActivityStream
		if err := rows.Scan(
			&i.ActivityID,
			pq.Array(&i.TimeOffsetS),
			pq.Array(&i.Hr),
			pq.Array(&i.PaceSPerKm),
			pq.Array(&i.Cadence),
			pq.Array(&i.PowerW),
			pq.Array(&i.AltitudeM),
			pq.Array(&i.Lat),
			pq.Array(&i.Lng),
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWellnessByUser = `-- name: ListWellnessByUser :many
SELECT id, user_id, date, metric_key, value_num, value_json, source, ingested_at FROM wellness_metrics
WHERE user_id = $1 AND date >= $2
ORDER BY date ASC
`

type ListWellnessByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) ListWellnessByUser(ctx context.Context, arg ListWellnessByUserParams) ([]WellnessMetric, error) {
	rows, err := q.db.QueryContext(ctx, listWellnessByUser, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WellnessMetric
	for rows.Next() {
		var i WellnessMetric
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.MetricKey,
			&i.ValueNum,
			&i.ValueJson,
			&i.Source,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
