// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: null.sql

package database

import (
	"context"
)

const null = `-- name: Null :one
SELECT 1
`

func (q *Queries) Null(ctx context.Context) (int, error) {
	row := q.db.QueryRow(ctx, null)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}
