// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPlannedWorkout = `-- name: GetPlannedWorkout :one
SELECT id, plan_id, user_id, scheduled_date, workout_type, description, target_distance_m, target_duration_s, structure, completed_activity_id, created_at, garmin_workout_id, garmin_schedule_id FROM planned_workouts WHERE id = $1
`

func (q *Queries) GetPlannedWorkout(ctx context.Context, id uuid.UUID) (PlannedWorkout, error) {
	row := q.db.QueryRowContext(ctx, getPlannedWorkout, id)
	var i PlannedWorkout
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UserID,
		&i.ScheduledDate,
		&i.WorkoutType,
		&i.Description,
		&i.TargetDistanceM,
		&i.TargetDurationS,
		&i.Structure,
		&i.CompletedActivityID,
		&i.CreatedAt,
		&i.GarminWorkoutID,
		&i.GarminScheduleID,
	)
	return i, err
}

const setPlannedWorkoutGarmin = `-- name: SetPlannedWorkoutGarmin :exec
UPDATE planned_workouts
SET garmin_workout_id = $2, garmin_schedule_id = $3
WHERE id = $1
`

type SetPlannedWorkoutGarminParams struct {
	ID               uuid.UUID     `json:"id"`
	GarminWorkoutID  sql.NullInt64 `json:"garmin_workout_id"`
	GarminScheduleID sql.NullInt64 `json:"garmin_schedule_id"`
}

func (q *Queries) SetPlannedWorkoutGarmin(ctx context.Context, arg SetPlannedWorkoutGarminParams) error {
	_, err := q.db.ExecContext(ctx, setPlannedWorkoutGarmin, arg.ID, arg.GarminWorkoutID, arg.GarminScheduleID)
	return err
}
