// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStravaConnection(ctx context.Context, arg CreateStravaConnectionParams) (StravaConnection, error)
	CreateUser(ctx context.Context, displayName sql.NullString) (User, error)
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteGarminConnection(ctx context.Context, userID uuid.UUID) error
	DeleteSession(ctx context.Context, id string) error
	GetActivityStream(ctx context.Context, activityID uuid.UUID) (ActivityStream, error)
	GetGarminConnection(ctx context.Context, userID uuid.UUID) (GarminConnection, error)
	GetSessionUser(ctx context.Context, id string) (GetSessionUserRow, error)
	GetStravaConnectionByAthleteID(ctx context.Context, athleteID int64) (StravaConnection, error)
	ListActivitiesByUser(ctx context.Context, arg ListActivitiesByUserParams) ([]Activity, error)
	ListActivityStreamsByUser(ctx context.Context, arg ListActivityStreamsByUserParams) ([]ActivityStream, error)
	ListGarminConnections(ctx context.Context) ([]GarminConnection, error)
	ListWellnessByUser(ctx context.Context, arg ListWellnessByUserParams) ([]WellnessMetric, error)
	Null(ctx context.Context) (int32, error)
	UpdateGarminLastSync(ctx context.Context, arg UpdateGarminLastSyncParams) error
	UpdateStravaTokens(ctx context.Context, arg UpdateStravaTokensParams) error
	UpsertActivity(ctx context.Context, arg UpsertActivityParams) (uuid.UUID, error)
	UpsertActivityStream(ctx context.Context, arg UpsertActivityStreamParams) error
	UpsertGarminConnection(ctx context.Context, arg UpsertGarminConnectionParams) (GarminConnection, error)
	UpsertWellnessMetric(ctx context.Context, arg UpsertWellnessMetricParams) error
}

var _ Querier = (*Queries)(nil)
