// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	Null(ctx context.Context) (int, error)
}

var _ Querier = (*Queries)(nil)
