// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wellness.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const upsertWellnessMetric = `-- name: UpsertWellnessMetric :exec
INSERT INTO wellness_metrics (user_id, date, metric_key, value_num, value_json, source)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, date, metric_key, source) DO UPDATE
SET value_num   = EXCLUDED.value_num,
    value_json  = EXCLUDED.value_json,
    ingested_at = now()
`

type UpsertWellnessMetricParams struct {
	UserID    uuid.UUID             `json:"user_id"`
	Date      time.Time             `json:"date"`
	MetricKey string                `json:"metric_key"`
	ValueNum  sql.NullString        `json:"value_num"`
	ValueJson pqtype.NullRawMessage `json:"value_json"`
	Source    string                `json:"source"`
}

func (q *Queries) UpsertWellnessMetric(ctx context.Context, arg UpsertWellnessMetricParams) error {
	_, err := q.db.ExecContext(ctx, upsertWellnessMetric,
		arg.UserID,
		arg.Date,
		arg.MetricKey,
		arg.ValueNum,
		arg.ValueJson,
		arg.Source,
	)
	return err
}
