name: Quality (Docker)

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  compose:
    name: Docker Compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: docker compose build
